name: commercialcomputing
description: "A new Flutter project."
publish_to: 'none' # This line prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.9
  mime: ^1.0.0
  mime_type: ^1.0.0
  fluttertoast: ^8.0.9
  image_picker: ^0.8.4+6
  table_calendar: ^3.0.5
  file_picker: ^5.2.4
  http: ^0.13.3
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/home_appreciation_message.png
    - assets/images/home_calendar.png
    - assets/images/home_donation.png
    - assets/images/home_request.png
    - assets/images/home_profile.png
    - assets/images/donor_profile.png
    - assets/images/donors_homes.png




  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf
